version: '3'

services:
  database:
    restart: unless-stopped
    image: mongo:latest
    env_file: .env
    volumes:
      -  ./volume:/data/db
    ports:
      - '$DB_PORT:$DB_PORT'
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:root

  bot:
    restart: always
    env_file: .env
    build: 
      context: .
      dockerfile: dockerfiles/bot      
      target: debug
      args:
        - 'BOT_TOKEN=$BOT_TOKEN'
        - 'WEBHOOK=$WEBHOOK'
        - 'WEB_SERVER_HOST=$WEB_SERVER_HOST'
        - 'WEB_SERVER_PORT=$WEB_SERVER_PORT'
        - 'PATH_TO_PEM=$PATH_TO_PEM'
        - 'PATH_TO_KEY=$PATH_TO_KEY'
        - 'WEBHOOK_PATH=$WEBHOOK_PATH'
    environment:
      - DB_HOST=database # task_dealer-database-1 # this is a fucking hardcode piece of shit but its works (idk how to fix it)

    ports:
      - '443:$WEB_SERVER_PORT'
      - '7200:7200' # debug port